allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  prisma: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ramz001-cinema/contracts'
  - '@ramz001-cinema/passport'
  - '@ramz001-cinema/core'